fix build error and minor issues

diff --git a/root/usr/local/bin/backup b/root/usr/local/bin/backup
--- a/root/usr/local/bin/backup
+++ b/root/usr/local/bin/backup
@@ -2,11 +2,16 @@
 . /usr/local/bin/with-env
 set -eo pipefail
 
-function logf() { echo "$(logging "BACKUP" "$1")"; }
+function logf() { logging "BACKUP" "$1"; }
 
 if pidof -o %PPID -x "$(basename "$0")">/dev/null; then
-  logf "Already in progress. Aborting!"
+  >&2 logf "Already in progress. Aborting!"
 	exit 3
+fi
+
+if [[ -z "${RESTIC_BACKUP_SOURCES:-}" ]]; then
+  >&2 logf "Please set RESTIC_BACKUP_SOURCES to proceed. Exiting..."
+  exit 1
 fi
 
 trap run_exit_commands EXIT
diff --git a/root/usr/local/bin/check b/root/usr/local/bin/check
--- a/root/usr/local/bin/check
+++ b/root/usr/local/bin/check
@@ -2,10 +2,10 @@
 . /usr/local/bin/with-env
 set -euo pipefail
 
-function logf() { echo "$(logging "CHECK" "$1")"; }
+function logf() { logging "CHECK" "$1"; }
 
 if pidof -o %PPID -x "$(basename "$0")">/dev/null; then
-  logf "Already in progress. Aborting!"
+  >&2 logf "Already in progress. Aborting!"
 	exit 3
 fi
 
