INIT_CHECK_CRON to allow mutually exclusive cron jobs at your own risk
* another check to avoid duplicate running of restic process
* separate scheduling cron jobs and run on startups
* some improvements

diff --git a/root/usr/local/bin/backup b/root/usr/local/bin/backup
--- a/root/usr/local/bin/backup
+++ b/root/usr/local/bin/backup
@@ -8,6 +8,10 @@ if pidof -o %PPID -x "$(basename "$0")">/dev/null; then
   >&2 logf "Already in progress. Aborting!"
 	exit 3
 fi
+if pidof -o %PPID -x restic>/dev/null; then
+  >&2 logf "'restic' process is still running. Aborting!"
+	exit 3
+fi
 
 if [[ -z "${RESTIC_BACKUP_SOURCES:-}" ]]; then
   >&2 logf "Please set RESTIC_BACKUP_SOURCES to proceed. Exiting..."
